server:
  port: 8082
spring:
  application:
    name: 'customer service'
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:customers
      username: sa
      password:
      driverClassName: org.h2.Driver

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka